### ISSUE TITLE
Not Able to Receive Data

### ISSUE THREAD

**Issue by rrohitesh** [zbum/tcp-communication-service#2]
Hello,

I am trying to receive the data as a form of packets over the tcp. But, i am not able to receive the the in actual form its coming in special character.

XQ#& ʍ�

But, when i am doing telnet its coming proper. The one which is not coming proper is sending by a device.

**Comment by zbum** [comment]
@rrohitesh Did you send binary data not ascii? @

**Comment by rrohitesh** [comment]
Yes i belive device is sending in that format only. Do I need to modify anything ?

**Comment by rrohitesh** [comment]
Do I need to modify anything ?

**Comment by zbum** [comment]
@rrohitesh  this source is only for ascii!
If you want this project to receive binary data, replace StringEncoder, StringDecoder with  ByteArrayEncoder, ByteArrayDecoder in [SomethingChannelInitializer.java.](https://github.com/zbum/netty-spring-example/blob/master/src/main/java/com/zbum/example/socket/server/netty/handler/SomethingChannelInitializer.java)
And change casting logic in [SomethingServerHandler.java](https://github.com/zbum/netty-spring-example/blob/master/src/main/java/com/zbum/example/socket/server/netty/handler/SomethingServerHandler.java)

**Comment by rrohitesh** [comment]
Thanks i will try this . Its sending data in HEX format.

**Comment by rrohitesh** [comment]
@zbum after changing to bytearraydecoder i am receiving the packets but its not proper sometimes half packets are coming and sometime full. 

Do i need to handle them through java code or is there any way?

**Comment by zbum** [comment]
I think you'd better design protocol for your application. 
It's not proper to determine finish of message flush by flush. Can you define end of message.

**Comment by zbum** [comment]
not issue for this code.
so close.
