### ISSUE TITLE
项目无法运行

### ISSUE THREAD

**Issue by zhangwei941913953** [zbum/tcp-communication-service#6]
1，TCPServer.java类中tcpPort未初始化，却在start方法中直接使用，springboot也没有自动初始化，导致server启动就抛出空指向异常
2，SomethingServerHandler.java中没对log进行初始化，却在代码中反复用到log变量。
项目无法运行

**Comment by zbum** [comment]
Thank you. Can you recheck with master branch?

**Comment by zbum** [comment]
I'll close this issue. @zhangwei941913953 
If you still want to fix this, please reopen this issue.
